# 背景

背景为3*2*1的神经网络，训练样本只有一个:   
x = [0.5, -0.2, -0.1]   
y = [0.4]

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
inputs = [0.5, -0.2, 0.1]
targets = [0.4]
input_hidden_weight = np.array([[0.1, 0.4, -0.3], [-0.2, 0.5, 0.2]])
hidden_output_weight = np.array([[0.3, -0.1]])
learning_rate=0.5

In [11]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

# 前向传播

In [12]:
z_1 = np.dot(input_hidden_weight, inputs)
z_1

array([-0.06, -0.18])

In [13]:
a_1 = sigmoid(z_1)
a_1

array([ 0.4850045 ,  0.45512111])

In [14]:
z_2 = np.dot(hidden_output_weight, a_1)
z_2

array([ 0.09998924])

In [15]:
y = sigmoid(z_2)
y

array([ 0.5249765])

# 反向传播

In [16]:
# output layer's error
output_error = targets - y
output_error

array([-0.1249765])

In [43]:
# output layer's gradient
output_gradient_1 = output_error * y * (1 - y) * a_1[0]
output_gradient_2 = output_error * y * (1 - y) * a_1[1]
output_gradient = np.array([output_gradient_1[0], output_gradient_2[0]])
output_gradient

array([-0.01511573, -0.01418438])

In [48]:
# output layer's gradient 的矩阵实现
output_gradient = output_error * y * (1 - y) * a_1
output_gradient

array([-0.01511573, -0.01418438])

In [44]:
# hidden layer's error
hidden_error = np.dot(output_error, hidden_output_weight)
hidden_error

array([-0.03749295,  0.01249765])

In [45]:
# hidden layer's gradient
hidden_gradient_01 = hidden_error[0] * (1 - a_1[0]) * a_1[0] * inputs[0]
hidden_gradient_02 = hidden_error[0] * (1 - a_1[0]) * a_1[0] * inputs[1]
hidden_gradient_03 = hidden_error[0] * (1 - a_1[0]) * a_1[0] * inputs[2]

hidden_gradient_11 = hidden_error[1] * (1 - a_1[1]) * a_1[1] * inputs[0]
hidden_gradient_12 = hidden_error[1] * (1 - a_1[1]) * a_1[1] * inputs[1]
hidden_gradient_13 = hidden_error[1] * (1 - a_1[1]) * a_1[1] * inputs[2]

hidden_gradient = np.array([
    [hidden_gradient_01, hidden_gradient_02, hidden_gradient_03],
    [hidden_gradient_11, hidden_gradient_12, hidden_gradient_13]
])
hidden_gradient

array([[-0.0046824 ,  0.00187296, -0.00093648],
       [ 0.00154962, -0.00061985,  0.00030992]])

In [117]:
# hidden layer's gradient 的矩阵实现
hidden_gradient = np.dot(np.array([hidden_error * a_1 * (1 - a_1)]).T, np.array([list(inputs)]))
hidden_gradient

array([[-0.0046824 ,  0.00187296, -0.00093648],
       [ 0.00154962, -0.00061985,  0.00030992]])

In [118]:
# new output weight
new_hidden_output_weight = hidden_output_weight + learning_rate * output_gradient
new_hidden_output_weight

array([[ 0.29244214, -0.10709219]])

In [119]:
# new hidden weight
new_input_hidden_weight = input_hidden_weight + learning_rate * hidden_gradient
new_input_hidden_weight

array([[ 0.0976588 ,  0.40093648, -0.30046824],
       [-0.19922519,  0.49969008,  0.20015496]])