In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [46]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

In [47]:
# 定义神经网络 4 -> 3 -> 2
N_input = 4
N_hidden = 3
N_output = 2

In [48]:
# 自定义随机输入
np.random.seed(42)
X = np.random.randn(4)
X

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [49]:
# 初始化 input -> hidden 权重
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_input_to_hidden

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623],
       [-0.19132802, -0.17249178, -0.05622875]])

In [50]:
# 初始化 hidden -> ouput 权重
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
weights_hidden_to_output

array([[-0.10128311,  0.03142473],
       [-0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763]])

In [51]:
# 计算 Hidden 层输入
hidden_layer_in = X.transpose().dot(weights_input_to_hidden)
hidden_layer_in

array([-0.34365494, -0.29801368,  0.00097362])

In [52]:
# 计算 Hidden 层输出
hidden_layer_out = sigmoid(hidden_layer_in)
hidden_layer_out

array([ 0.41492192,  0.42604313,  0.5002434 ])

In [53]:
# 计算 Output 层输入
output_layer_in = hidden_layer_out.transpose().dot(weights_hidden_to_output)
output_layer_in

array([-0.00739221, -0.05842573])

In [54]:
# 计算 Output 层输出
output_layer_out = sigmoid(output_layer_in)
output_layer_out

array([ 0.49815196,  0.48539772])