In [45]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

In [46]:
# Hyperparameters
n_hidden = 2  # number of hidden units
epochs = 1
learnrate = 0.5
x = [0.5, -0.2, 0.1]
y = [0.4]

n_records = 1 
n_features = 3

# Initialize weights
weights_input_hidden = np.array([[0.1, 0.4, -0.3], [-0.2, 0.5, 0.2]])
weights_hidden_output = np.array([[0.3, -0.1]])

In [47]:
# 前向传播
del_w_input_hidden = np.zeros(weights_input_hidden.shape)
del_w_hidden_output = np.zeros(weights_hidden_output.shape)

## Forward pass ##
hidden_input = np.dot(weights_input_hidden, x)
print hidden_input
hidden_output = sigmoid(hidden_input)
print hidden_output

output = sigmoid(np.dot(weights_hidden_output, hidden_output))
print output

[-0.06 -0.18]
[ 0.4850045   0.45512111]
[ 0.5249765]


In [48]:
# TODO: Calculate error term for the output unit
error = y - output
print error
output_error_term = error * output * (1 - output)
print output_error_term
del_w_hidden_output += output_error_term * hidden_output
print del_w_hidden_output

print learnrate * del_w_hidden_output
print weights_hidden_output
weights_hidden_output += learnrate * del_w_hidden_output
print weights_hidden_output

[-0.1249765]
[-0.03116616]
[[-0.01511573 -0.01418438]]
[[-0.00755786 -0.00709219]]
[[ 0.3 -0.1]]
[[ 0.29244214 -0.10709219]]
