In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
inputs = [0.5, -0.2, 0.1]
targets = [0.4]
test_w_i_h = np.array([[0.1, 0.4, -0.3], [-0.2, 0.5, 0.2]])
test_w_h_o = np.array([[0.3, -0.1]])
learning_rate=0.5

In [24]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

        self.assertTrue(np.allclose(network.weights_hidden_to_output, 
                                    np.array([[ 0.37275328, -0.03172939]])))
        
        self.assertTrue(np.allclose(network.weights_input_to_hidden,
                                    np.array([[ 0.10562014,  0.39775194, -0.29887597],
                                              [-0.20185996,  0.50074398,  0.19962801]])))

# 前向传播

In [25]:
z_1 = np.dot(test_w_i_h, inputs)
z_1

array([-0.06, -0.18])

In [26]:
a_1 = sigmoid(z_1)
a_1

array([ 0.4850045 ,  0.45512111])

In [27]:
z_2 = np.dot(test_w_h_o, a_1)
z_2

array([ 0.09998924])

In [28]:
y = sigmoid(z_2)
y

array([ 0.5249765])

# 反向传播

In [36]:
output_error = targets - y
output_error

array([-0.1249765])

In [48]:
# hiddan layer 的 gradient
gradient_0 = output_error * y * (1 - y) * (-a_1[0])
gradient_0

array([ 0.01511573])

In [47]:
weights_hidden_to_output_0 = test_w_h_o[0][0] - gradient_0 * learning_rate
weights_hidden_to_output_0

array([ 0.29244214])

In [42]:
gradient_1 = output_error * y * (1 - y) * (-a_1[1])
gradient_1

array([ 0.01418438])

In [46]:
weights_hidden_to_output_1 = test_w_h_o[0][1] - gradient_1 * learning_rate
weights_hidden_to_output_1

array([-0.10709219])

In [49]:
0.3 

0.17502350000000005

In [53]:
(0.4 - 0.5249765) * np.exp(-0.4850045 * 0.3 + 0.4512111 * 0.1)/pow(1 + np.exp(-0.4850045 * 0.3 + 0.4512111 * 0.1), 2) * 0.4850045

-0.015115432737832304

In [54]:
0.3 -0.015115432737832304

0.2848845672621677

In [59]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

In [60]:
inputs = [0.1, 0.3]
targets = [1]
test_w_i_h = np.array([[0.4, -0.2]])
test_w_h_o = np.array([[0.1]])
learning_rate=0.5

In [61]:
z_1 = np.dot(test_w_i_h, inputs)
z_1

array([-0.02])

In [63]:
a_1 = sigmoid(z_1)
a_1

array([ 0.49500017])

In [64]:
y = sigmoid(np.dot(test_w_h_o, a_1))
y

array([ 0.51237248])

In [66]:
output_error = (targets - y) * y * (1- y)  # Why these calls error
output_error

array([ 0.12183224])

In [69]:
hidden_error = np.dot(test_w_h_o, output_error) * a_1 * (1 - a_1)
hidden_error

array([ 0.0030455])

In [71]:
output_gradient = learning_rate * output_error * a_1
output_gradient

array([ 0.03015349])

In [73]:
hidden_gradient = learning_rate * hidden_error * inputs
hidden_gradient

array([ 0.00015228,  0.00045683])