# K Nearest Neighbor

## 加载数据

In [9]:
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

np.unique(iris_y)

print iris_X.shape
print iris_y.shape

(150, 4)
(150,)


## 将数据随机分成训练集和测试集

In [6]:
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]

iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

print iris_X_train.shape
print iris_y_train.shape
print iris_X_test.shape
print iris_y_test.shape

## 训练

In [7]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)

[1 2 1 0 0 0 2 1 2 0]
[1 1 1 0 0 0 2 1 2 0]


## 预测

In [8]:
print knn.predict(iris_X_test)
print iris_y_test

[1 2 1 0 0 0 2 1 2 0]
[1 1 1 0 0 0 2 1 2 0]
