# Support Vector Machine

## 加载数据

In [1]:
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]

print iris_X_train.shape
print iris_y_train.shape
print iris_X_test.shape
print iris_y_test.shape

print np.unique(iris_y)

(140, 4)
(140,)
(10, 4)
(10,)
[0 1 2]


## SVM训练

In [3]:
from sklearn import svm

svc = svm.SVC(kernel='linear')
svc.fit(iris_X_train, iris_y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

## 预测

In [5]:
print svc.predict(iris_X_test)
print iris_y_test

[1 2 1 0 0 0 2 1 2 0]
[1 1 1 0 0 0 2 1 2 0]


## 评分

In [6]:
svc.score(iris_X_test, iris_y_test)

0.90000000000000002