In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
import time

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print('Vectorized version: {} ms'.format(toc - tic))

Vectorized version: 0.0496559143066 ms


In [5]:
c  = 0
tic = time.time()

for i in range(10000000):
    c += a[i] * b[i]
toc = time.time()

print('for loop: {} ms'.format(toc - tic))

for loop: 6.3438141346 ms


In [6]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1) 

print a
print b

[[ 0.67230145  0.84683451 -0.47051865]
 [-1.60129679 -1.13480018 -0.38633064]
 [ 0.93786591 -0.41561701 -0.16850409]]
[[ 0.35429761]
 [ 2.73267374]
 [-0.52881207]]


In [7]:
a * b

array([[ 0.2381948 ,  0.30003145, -0.16670364],
       [-4.37582167, -3.10103866, -1.0557156 ],
       [-0.49595481,  0.21978329,  0.08910699]])

In [8]:
-0.14958623* 1.01214043

-0.1514022711542789

In [9]:
0.37954412 * 1.01214043

0.38415194882077164

In [13]:
np.zeros([3, 2])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [14]:
np.log(a)

/Users/chenhuan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in log
  if __name__ == '__main__':


array([[-0.39704846, -0.16624999,         nan],
       [        nan,         nan,         nan],
       [-0.0641483 ,         nan,         nan]])

In [15]:
a

array([[ 0.67230145,  0.84683451, -0.47051865],
       [-1.60129679, -1.13480018, -0.38633064],
       [ 0.93786591, -0.41561701, -0.16850409]])

In [18]:
a[0, 0]

0.6723014472427048